apiVersion: v1
name: locust
version: "0.32.1"
appVersion: 2.32.2
home: https://github.com/locustio/locust
icon: https://locust.io/static/img/logo.png
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
description: |
  A chart to install Locust, a scalable load testing tool written in Python.

  This chart will setup everything required to run a full distributed locust environment with any amount of workers.
